using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/BeadInfo")]
public partial class BeadInfo : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4767396431384418753UL,3982588816775351942UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public new System.String name
	{
		get => _name[Entity.Index];
		set => _name[Entity.Index] = value;
	}
	public System.String Type_Of_Bead
	{
		get => _Type_Of_Bead[Entity.Index];
		set => _Type_Of_Bead[Entity.Index] = value;
	}
	public System.Single Number_Of_Beads_On_Hand
	{
		get => _Number_Of_Beads_On_Hand[Entity.Index];
		set => _Number_Of_Beads_On_Hand[Entity.Index] = value;
	}
	public UnityEngine.Sprite Picture_Of_Bead => _Picture_Of_Bead[Entity.Index];
	public System.Single Price_Of_BeadStrand
	{
		get => _Price_Of_BeadStrand[Entity.Index];
		set => _Price_Of_BeadStrand[Entity.Index] = value;
	}
	public System.Single Number_Of_Beads_On_Strand
	{
		get => _Number_Of_Beads_On_Strand[Entity.Index];
		set => _Number_Of_Beads_On_Strand[Entity.Index] = value;
	}
	public System.String Bead_Size
	{
		get => _Bead_Size[Entity.Index];
		set => _Bead_Size[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4880611229024479559UL, 369652847959201724UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Type_Of_Bead;
	public static BansheeGz.BGDatabase.BGFieldString _Type_Of_Bead => _ufle12jhs77_Type_Of_Bead ?? (_ufle12jhs77_Type_Of_Bead = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5105042686097870343UL, 4478521550558106269UL), () => _ufle12jhs77_Type_Of_Bead = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Number_Of_Beads_On_Hand;
	public static BansheeGz.BGDatabase.BGFieldFloat _Number_Of_Beads_On_Hand => _ufle12jhs77_Number_Of_Beads_On_Hand ?? (_ufle12jhs77_Number_Of_Beads_On_Hand = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5000270233350780749UL, 17192403440994738849UL), () => _ufle12jhs77_Number_Of_Beads_On_Hand = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_Picture_Of_Bead;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _Picture_Of_Bead => _ufle12jhs77_Picture_Of_Bead ?? (_ufle12jhs77_Picture_Of_Bead = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5307244178994383635UL, 7521017248257770645UL), () => _ufle12jhs77_Picture_Of_Bead = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Price_Of_BeadStrand;
	public static BansheeGz.BGDatabase.BGFieldFloat _Price_Of_BeadStrand => _ufle12jhs77_Price_Of_BeadStrand ?? (_ufle12jhs77_Price_Of_BeadStrand = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5560159152862799048UL, 16159720137898974653UL), () => _ufle12jhs77_Price_Of_BeadStrand = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Number_Of_Beads_On_Strand;
	public static BansheeGz.BGDatabase.BGFieldFloat _Number_Of_Beads_On_Strand => _ufle12jhs77_Number_Of_Beads_On_Strand ?? (_ufle12jhs77_Number_Of_Beads_On_Strand = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5446382648682752906UL, 13715208859231753389UL), () => _ufle12jhs77_Number_Of_Beads_On_Strand = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Bead_Size;
	public static BansheeGz.BGDatabase.BGFieldString _Bead_Size => _ufle12jhs77_Bead_Size ?? (_ufle12jhs77_Bead_Size = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5019927447685820328UL, 10695908656212893346UL), () => _ufle12jhs77_Bead_Size = null));
}
