using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/StrandInfo")]
public partial class StrandInfo : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5400701889048641468UL,12791276249247057067UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public new System.String name
	{
		get => _name[Entity.Index];
		set => _name[Entity.Index] = value;
	}
	public System.String BeadNumber1NameUsed
	{
		get => _BeadNumber1NameUsed[Entity.Index];
		set => _BeadNumber1NameUsed[Entity.Index] = value;
	}
	public System.Single NumberOfBeads1Used
	{
		get => _NumberOfBeads1Used[Entity.Index];
		set => _NumberOfBeads1Used[Entity.Index] = value;
	}
	public System.Double TotalPriceOfBead1
	{
		get => _TotalPriceOfBead1[Entity.Index];
		set => _TotalPriceOfBead1[Entity.Index] = value;
	}
	public System.String BeadNumber2NameUsed
	{
		get => _BeadNumber2NameUsed[Entity.Index];
		set => _BeadNumber2NameUsed[Entity.Index] = value;
	}
	public System.Single NumberOfBeads2Used
	{
		get => _NumberOfBeads2Used[Entity.Index];
		set => _NumberOfBeads2Used[Entity.Index] = value;
	}
	public System.Double TotalPriceOfBead2
	{
		get => _TotalPriceOfBead2[Entity.Index];
		set => _TotalPriceOfBead2[Entity.Index] = value;
	}
	public System.String BeadNumber3NameUsed
	{
		get => _BeadNumber3NameUsed[Entity.Index];
		set => _BeadNumber3NameUsed[Entity.Index] = value;
	}
	public System.Single NumberOfBeads3Used
	{
		get => _NumberOfBeads3Used[Entity.Index];
		set => _NumberOfBeads3Used[Entity.Index] = value;
	}
	public System.Double TotalPriceOfBead3
	{
		get => _TotalPriceOfBead3[Entity.Index];
		set => _TotalPriceOfBead3[Entity.Index] = value;
	}
	public System.String BeadNumber4NameUsed
	{
		get => _BeadNumber4NameUsed[Entity.Index];
		set => _BeadNumber4NameUsed[Entity.Index] = value;
	}
	public System.Single NumberOfBeads4Used
	{
		get => _NumberOfBeads4Used[Entity.Index];
		set => _NumberOfBeads4Used[Entity.Index] = value;
	}
	public System.Double TotalPriceOfBead4
	{
		get => _TotalPriceOfBead4[Entity.Index];
		set => _TotalPriceOfBead4[Entity.Index] = value;
	}
	public System.Single HowLongToMakeStrand
	{
		get => _HowLongToMakeStrand[Entity.Index];
		set => _HowLongToMakeStrand[Entity.Index] = value;
	}
	public System.Double HourlyWage
	{
		get => _HourlyWage[Entity.Index];
		set => _HourlyWage[Entity.Index] = value;
	}
	public System.Double TotalLaborCost
	{
		get => _TotalLaborCost[Entity.Index];
		set => _TotalLaborCost[Entity.Index] = value;
	}
	public System.Double CopperWireCost
	{
		get => _CopperWireCost[Entity.Index];
		set => _CopperWireCost[Entity.Index] = value;
	}
	public System.Double StrandCost
	{
		get => _StrandCost[Entity.Index];
		set => _StrandCost[Entity.Index] = value;
	}
	public System.Double StrandCostWithWireAndLabor
	{
		get => _StrandCostWithWireAndLabor[Entity.Index];
		set => _StrandCostWithWireAndLabor[Entity.Index] = value;
	}
	public System.Double MarkupCostOfStrand
	{
		get => _MarkupCostOfStrand[Entity.Index];
		set => _MarkupCostOfStrand[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4872942024260678291UL, 6578441052149620375UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_BeadNumber1NameUsed;
	public static BansheeGz.BGDatabase.BGFieldString _BeadNumber1NameUsed => _ufle12jhs77_BeadNumber1NameUsed ?? (_ufle12jhs77_BeadNumber1NameUsed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5747353376999868488UL, 15151920889073442688UL), () => _ufle12jhs77_BeadNumber1NameUsed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_NumberOfBeads1Used;
	public static BansheeGz.BGDatabase.BGFieldFloat _NumberOfBeads1Used => _ufle12jhs77_NumberOfBeads1Used ?? (_ufle12jhs77_NumberOfBeads1Used = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4646122612725007290UL, 16996222691622376108UL), () => _ufle12jhs77_NumberOfBeads1Used = null));
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_TotalPriceOfBead1;
	public static BansheeGz.BGDatabase.BGFieldDouble _TotalPriceOfBead1 => _ufle12jhs77_TotalPriceOfBead1 ?? (_ufle12jhs77_TotalPriceOfBead1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(4917222903246246379UL, 12696132172557082538UL), () => _ufle12jhs77_TotalPriceOfBead1 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_BeadNumber2NameUsed;
	public static BansheeGz.BGDatabase.BGFieldString _BeadNumber2NameUsed => _ufle12jhs77_BeadNumber2NameUsed ?? (_ufle12jhs77_BeadNumber2NameUsed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4912812870039471287UL, 17226379675619611049UL), () => _ufle12jhs77_BeadNumber2NameUsed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_NumberOfBeads2Used;
	public static BansheeGz.BGDatabase.BGFieldFloat _NumberOfBeads2Used => _ufle12jhs77_NumberOfBeads2Used ?? (_ufle12jhs77_NumberOfBeads2Used = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5414071360194442551UL, 10531632166487916974UL), () => _ufle12jhs77_NumberOfBeads2Used = null));
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_TotalPriceOfBead2;
	public static BansheeGz.BGDatabase.BGFieldDouble _TotalPriceOfBead2 => _ufle12jhs77_TotalPriceOfBead2 ?? (_ufle12jhs77_TotalPriceOfBead2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5077691896726791229UL, 10797919806378596503UL), () => _ufle12jhs77_TotalPriceOfBead2 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_BeadNumber3NameUsed;
	public static BansheeGz.BGDatabase.BGFieldString _BeadNumber3NameUsed => _ufle12jhs77_BeadNumber3NameUsed ?? (_ufle12jhs77_BeadNumber3NameUsed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4813953048727751867UL, 8382437753205436602UL), () => _ufle12jhs77_BeadNumber3NameUsed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_NumberOfBeads3Used;
	public static BansheeGz.BGDatabase.BGFieldFloat _NumberOfBeads3Used => _ufle12jhs77_NumberOfBeads3Used ?? (_ufle12jhs77_NumberOfBeads3Used = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4927620748299357776UL, 10611746892515512505UL), () => _ufle12jhs77_NumberOfBeads3Used = null));
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_TotalPriceOfBead3;
	public static BansheeGz.BGDatabase.BGFieldDouble _TotalPriceOfBead3 => _ufle12jhs77_TotalPriceOfBead3 ?? (_ufle12jhs77_TotalPriceOfBead3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5292158988336610390UL, 6153748622298118309UL), () => _ufle12jhs77_TotalPriceOfBead3 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_BeadNumber4NameUsed;
	public static BansheeGz.BGDatabase.BGFieldString _BeadNumber4NameUsed => _ufle12jhs77_BeadNumber4NameUsed ?? (_ufle12jhs77_BeadNumber4NameUsed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5485383178322505693UL, 7076949969147179926UL), () => _ufle12jhs77_BeadNumber4NameUsed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_NumberOfBeads4Used;
	public static BansheeGz.BGDatabase.BGFieldFloat _NumberOfBeads4Used => _ufle12jhs77_NumberOfBeads4Used ?? (_ufle12jhs77_NumberOfBeads4Used = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4960211475338359749UL, 9928400895400833442UL), () => _ufle12jhs77_NumberOfBeads4Used = null));
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_TotalPriceOfBead4;
	public static BansheeGz.BGDatabase.BGFieldDouble _TotalPriceOfBead4 => _ufle12jhs77_TotalPriceOfBead4 ?? (_ufle12jhs77_TotalPriceOfBead4 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5202561640653446860UL, 16879159866053314987UL), () => _ufle12jhs77_TotalPriceOfBead4 = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_HowLongToMakeStrand;
	public static BansheeGz.BGDatabase.BGFieldFloat _HowLongToMakeStrand => _ufle12jhs77_HowLongToMakeStrand ?? (_ufle12jhs77_HowLongToMakeStrand = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5466412671142952055UL, 18003856241095939739UL), () => _ufle12jhs77_HowLongToMakeStrand = null));
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_HourlyWage;
	public static BansheeGz.BGDatabase.BGFieldDouble _HourlyWage => _ufle12jhs77_HourlyWage ?? (_ufle12jhs77_HourlyWage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5372763682785668263UL, 15497412728264392064UL), () => _ufle12jhs77_HourlyWage = null));
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_TotalLaborCost;
	public static BansheeGz.BGDatabase.BGFieldDouble _TotalLaborCost => _ufle12jhs77_TotalLaborCost ?? (_ufle12jhs77_TotalLaborCost = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(4635444528316882824UL, 12133833865238094215UL), () => _ufle12jhs77_TotalLaborCost = null));
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_CopperWireCost;
	public static BansheeGz.BGDatabase.BGFieldDouble _CopperWireCost => _ufle12jhs77_CopperWireCost ?? (_ufle12jhs77_CopperWireCost = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(4770214262642415996UL, 10532668952792847511UL), () => _ufle12jhs77_CopperWireCost = null));
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_StrandCost;
	public static BansheeGz.BGDatabase.BGFieldDouble _StrandCost => _ufle12jhs77_StrandCost ?? (_ufle12jhs77_StrandCost = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5475762724359557830UL, 1845190158441399426UL), () => _ufle12jhs77_StrandCost = null));
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_StrandCostWithWireAndLabor;
	public static BansheeGz.BGDatabase.BGFieldDouble _StrandCostWithWireAndLabor => _ufle12jhs77_StrandCostWithWireAndLabor ?? (_ufle12jhs77_StrandCostWithWireAndLabor = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5449915453448421885UL, 253663923467310260UL), () => _ufle12jhs77_StrandCostWithWireAndLabor = null));
	private static BansheeGz.BGDatabase.BGFieldDouble _ufle12jhs77_MarkupCostOfStrand;
	public static BansheeGz.BGDatabase.BGFieldDouble _MarkupCostOfStrand => _ufle12jhs77_MarkupCostOfStrand ?? (_ufle12jhs77_MarkupCostOfStrand = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldDouble>(MetaDefault, new BGId(5733804382204700077UL, 4920397374194374039UL), () => _ufle12jhs77_MarkupCostOfStrand = null));
}
